/*
 * Netsoc IAM
 *
 * API for managing and authenticating Netsoc users. 
 *
 * API version: 1.0.8
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package iam
// Error struct for Error
type Error struct {
	// Message explaining the error
	Message string `json:"message"`
}
