/*
 * Netsoc IAM
 *
 * API for managing and authenticating Netsoc users. 
 *
 * API version: 1.0.4
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package iam
// TokenResponse struct for TokenResponse
type TokenResponse struct {
	Token string `json:"token,omitempty"`
}
