/*
 * Netsoc IAM
 *
 * API for managing and authenticating Netsoc users. 
 *
 * API version: 1.0.9
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package iam
import (
	"time"
)
// UserMeta Metadata about the user, not modifiable.
type UserMeta struct {
	// Date and time at which the user was created
	Created time.Time `json:"created"`
	// Date and time at which the user was last updated
	Updated time.Time `json:"updated"`
}
