/*
 * Netsoc IAM
 *
 * API for managing and authenticating Netsoc users. 
 *
 * API version: 1.0.10
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package iam
// ResetPasswordRequest struct for ResetPasswordRequest
type ResetPasswordRequest struct {
	Password string `json:"password,omitempty"`
}
