/*
 * Netsoc IAM
 *
 * API for managing and authenticating Netsoc users. 
 *
 * API version: 1.0.3
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package iam
// LoginRequest struct for LoginRequest
type LoginRequest struct {
	Password string `json:"password"`
}
