log_level: INFO
http:
  listen_address: ':8080'
  cors_allow_origin: '*'
db:
  host: db
  user: iamd
  password: hunter2
  password_file: /run/secrets/db.txt
  database: iamd
  timezone: 'Europe/Dublin'
  dsn_extra: ''
  soft_delete: false
mail:
  from: '"Netsoc IAM" <iam@netsoc.ie>'
  reply_to: '"Netsoc support" <support@netsoc.ie>'
  verify_url: 'https://account.netsoc.ie/verify?token={{.Token}}'
  reset_url: 'https://account.netsoc.ie/reset?token={{.Token}}'
  smtp:
    host: mail
    port: 587
    username: iam@netsoc.ie
    password: hunter2
    password_file: /run/secrets/smtp.txt
    tls: true
jwt:
  key: QUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUE=
  key_file: /run/secrets/jwt_key.bin
  issuer: netsoc
  login_validity: '8760h'
  email_validity: '24h'
root_password: hunter22
root_password_file: /run/secrets/root.txt
reserved_usernames: []
