version: '3'
services:
  db:
    image: postgres:alpine
    environment:
      - POSTGRES_USER=iamd
      - POSTGRES_PASSWORD=hunter2
    ports:
      - 5432:5432
    volumes:
      - ./data/pgdata:/var/lib/postgresql/data

  app:
    image: ghcr.io/netsoc/iamd:dev
    build:
      context: .
      dockerfile: Dockerfile.dev
    environment:
      - IAMD_LOG_LEVEL=debug
      - IAMD_HTTP_ADDRESS=:8080
      - IAMD_DB_SOFT_DELETE=false
      - IAMD_JWT_KEY=QUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUE=
    ports:
      - 8080:8080
    volumes:
      - .:/usr/local/lib/iamd
    user: '1000:1000'
