version: '3'
services:
  db:
    image: postgres:alpine
    environment:
      - POSTGRES_USER=iamd
      - POSTGRES_PASSWORD=hunter2
    ports:
      - 5432:5432
    volumes:
      - ./data/pgdata:/var/lib/postgresql/data

  mail:
    image: ndamiens/mailslurper
    ports:
      - 8181:8080
      - 8085:8085

  app:
    image: ghcr.io/netsoc/iamd:dev
    build:
      context: .
      dockerfile: Dockerfile.dev
    environment:
      - IAMD_LOG_LEVEL=debug
      - IAMD_HTTP_LISTEN_ADDRESS=:8080
      - IAMD_DB_SOFT_DELETE=false
      - IAMD_JWT_KEY=QUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUE=
      - IAMD_MAIL_SMTP_PORT=2500
      - IAMD_RESERVED_USERNAMES=forbidden
    ports:
      - 8080:8080
      - 8008:8008
    volumes:
      - .:/usr/local/lib/iamd
      - ./config.yaml:/run/config/iamd.yaml:ro
    user: '1000:1000'
