apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "iamd.fullname" . }}
  labels:
    {{- include "iamd.labels" . | nindent 4 }}
data:
  {{- with .Values.config }}
  iamd.yaml: |
    {{- toYaml . | nindent 4 }}
  {{- end }}
