apiVersion: v1
kind: Secret
metadata:
  name: {{ include "iamd.fullname" . }}
  labels:
    {{- include "iamd.labels" . | nindent 4 }}
data:
  smtp.txt: {{ .Values.secrets.smtpPassword | b64enc }}
  jwt_key.bin: {{ include "iamd.jwtKey" . }}
  root.txt: {{ include "iamd.rootPassword" . | b64enc }}
{{- if not .Values.postgresql.enabled }}
  postgresql.txt: {{ .Values.postgresql.postgresqlPassword | b64enc }}
{{- end }}
