apiVersion: v1
kind: Service
metadata:
  name: {{ include "iamd.fullname" . }}
  labels:
    {{- include "iamd.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  {{- if .Values.config.ma1sd.http_address }}
    - port: {{ .Values.service.ma1sdPort }}
      targetPort: ma1sd
      protocol: TCP
      name: ma1sd
  {{- end }}
  selector:
    {{- include "iamd.selectorLabels" . | nindent 4 }}
