name: Build

on:
  push:
    branches:
      - master
    paths-ignore:
      - charts/**

jobs:
  tests:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2

      - uses: testspace-com/setup-testspace@v1
        with:
          domain: ${{ github.repository_owner }}
          token:  ${{ secrets.TESTSPACE_TOKEN }}

      - uses: actions/setup-go@v2
        with:
          go-version: '1.16.x'

      - name: Download dependencies
        run: |
          go mod download

          go get github.com/jstemmer/go-junit-report
          go get github.com/t-yuki/gocover-cobertura

          # Needed for test build to succeed
          go-bindata -fs -o internal/data/bindata.go -pkg data -prefix static/ static/...

      - name: Run tests
        id: tests
        run: |
          if go test -v -coverprofile=coverage.txt -tags test ./... 2>&1 > tests.log; then
            echo "::set-output name=passed::yes"
          else
            echo "::set-output name=passed::no"
          fi

      - name: Publish results to Testspace
        run: |
          go-junit-report < tests.log > results.xml
          gocover-cobertura < coverage.txt > coverage.xml

          testspace results.xml coverage.xml

      - name: Check tests passed
        run: |
          if [ "${{ steps.tests.outputs.passed }}" = "yes" ]; then
            echo "Tests passed."
          else
            echo "Tests failed!"
            exit 1
          fi

  docker:
    runs-on: ubuntu-20.04
    needs: [tests]

    env:
      CR_PAT_USER: devplayer0
      REPO: ghcr.io/netsoc/iamd

    steps:
      - uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        with:
          driver-opts: image=moby/buildkit:master

      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Log into GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ env.CR_PAT_USER }}
          password: ${{ secrets.CI_PAT }}

      - id: vars
        name: Generate build vars
        run: |
          SHA="${{ github.sha }}"
          echo "::set-output name=tag::"${SHA:0:8}-$(date +%s)Z""

      - name: Build
        uses: docker/build-push-action@v2
        with:
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache
          load: true
          tags: |
            ${{ env.REPO }}:${{ steps.vars.outputs.tag }}
            ${{ env.REPO }}:latest

      # Pushing to an existing tag doesn't seem to work with buildx :(
      - name: Push
        run: docker push --all-tags "$REPO"
