on: [create]

name: Release

jobs:
  build:
    runs-on: ubuntu-latest
    if: ${{ github.event.ref_type == 'tag' }}

    env:
      DOCKER_REPO: ghcr.io/netsoc/iamd

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Debug vars
        run: |
          echo "${{ github.event.ref }}:${{ github.sha }} (${{ github.ref }})"
          echo "Changelog: "
          git log --pretty=format:"- %s" "$(git describe --tags --abbrev=0 ${{ github.event.ref }}^)"..${{ github.event.ref }}

      #- name: Tag Docker image
      #  run: |
      #    docker pull "$DOCKER_REPO:${{ github.sha }}"
      #    docker tag "$DOCKER_REPO:${{ github.sha }}" "$DOCKER_REPO:${{ github.ref }}"

      #- name: Create Release
      #  id: create_release
      #  uses: actions/create-release@v1
      #  env:
      #    GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
      #  with:
      #    tag_name: ${{ github.ref }}
      #    release_name: Release ${{ github.ref }}
      #    body: |
      #      Changes in this Release
      #      - First Change
      #      - Second Change
      #    draft: false
      #    prerelease: false
